package vindbrein.dao.app;

import java.util.LinkedHashMap;
import java.util.List;

import org.hibernate.SQLQuery;
import org.hibernate.SessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Repository;

import vindbrein.domain.model.OfertaLaboral;
import vindbrein.domain.model.Postulante;

@Repository
public class CoreDAO {
	
	@Autowired
	@Qualifier("sessionFactory")
	private SessionFactory sessionFactory;
	
	
	public LinkedHashMap<String, Integer> getVectorOfferSelfDescription(OfertaLaboral ofertaLaboral){
		
		LinkedHashMap<String, Integer> result = new LinkedHashMap<String, Integer>();
		

		SQLQuery query = getSessionFactory()
				.getCurrentSession().createSQLQuery(""
						+" select r1.vector"
						+"       ,r1.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"        if (cv.cava_valor_code in (select fk_bene_id from oferta_beneficio where fk_ofla_id = :oflaId ) ,1,0) vector"
						+"	   ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'beneflab'"						
						+" order by cv.cava_id asc"
						+"  ) r1"
						+"  "
						+"  union all"
						+"  "
						+"  select r2.vector"
						+"        ,r2.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"         if (cv.cava_cota_minima <= (select ofla_salario from oferta_laboral where ofla_id = :oflaId)"
						+"             and cv.cava_cota_maxima >= (select ofla_salario from oferta_laboral where ofla_id = :oflaId)"
						+"            ,1"
						+"            ,0) vector"
						+"		,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'salario'"						
						+" order by cv.cava_id asc"
						+"  ) r2"
						+"  "
						+"  union all"
						+"  "
						+"  select r3.vector"
						+"        ,r3.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"        if (cv.cava_valor_code in (select fk_tiho_id from oferta_laboral where ofla_id = :oflaId ) ,1,0) vector"
						+"	   ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'tipohor'"						
						+" order by cv.cava_id asc"
						+"  ) r3"
						+"  "
						+"  union all"
						+"  "
						+"  select r4.vector"
						+"        ,r4.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"   if (cv.cava_valor_code in (select org.fk_sect_id"
						+"                               from oferta_laboral ol,"
						+"                                    organizacion   org"
						+"                              where ol.ofla_id = :oflaId"
						+"                               and org.orga_id = ol.fk_orga_id"
						+"							  and org.orga_estado = 'V') ,1,0) vector"
						+"   ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'sector'"						
						+" order by cv.cava_id asc"
						+"  ) r4"
						+"  "
						+"  union all"
						+"  "
						+"  select r5.vector"
						+"        ,r5.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"     if (cv.cava_valor_code in (select org.fk_dior_id"
						+"                                 from oferta_laboral ol,"
						+"                                      organizacion   org"
						+"                                where ol.ofla_id = :oflaId"
						+"                                  and org.orga_id = ol.fk_orga_id"
						+"								 and org.orga_estado = 'V') ,1,0) vector"
						+"    ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'dimensemp'"						
						+" order by cv.cava_id asc"
						+"  ) r5"
						+"  "
						+"  union all"
						+"  "
						+"  select r6.vector"
						+"        ,r6.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"    if (cv.cava_valor_code in (select pu.fk_nipu_id"
						+"                                      from oferta_laboral ol,"
						+"                                           puesto pu"
						+"                                     where 1=1"
						+"                                      and ol.fk_pues_id = pu.pues_id"
						+"                                      and ol.ofla_id = :oflaId ) ,1,0) vector"
						+"    ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'tipopuest'"						
						+" order by cv.cava_id asc"
						+"  ) r6");
		
		query.setParameter("oflaId", ofertaLaboral.getOflaId());
		
		List<Object[]> list = query.list();
		
		for (int i = 0; i < list.size(); i++) {
			Integer value = (Integer)list.get(i)[0];
			String key = (String)list.get(i)[1];
			
			System.out.println(key+" "+value);
			
			result.put(key, value);
		}
		
		return result;		
	}
	
	public LinkedHashMap<String, Integer> getVectorOfferPreference(OfertaLaboral ofertaLaboral){
		LinkedHashMap<String, Integer> result = new LinkedHashMap<String, Integer>();
		

		SQLQuery query = getSessionFactory()
				.getCurrentSession().createSQLQuery(""
						+" select r1.vector"
						+"       ,r1.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"    if (ol.ofla_sexo = cv.cava_valor_code,1,0) vector"
						+"    ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+"     ,oferta_laboral      ol"
						+" where 1=1"
						+" and ol.ofla_id = :oflaId"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'sexo'"						
						+" order by cv.cava_id asc"
						+"  ) r1"
						+"  "
						+"  union all"
						+" "
						+" select r2.vector"
						+"       ,r2.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"    if (ol.ofla_edad >= cv.cava_cota_minima"
						+"     and ol.ofla_edad <= cv.cava_cota_maxima,1,0) vector"
						+"    ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+"     ,oferta_laboral      ol"
						+" where 1=1"
						+" and ol.ofla_id = :oflaId"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'edad'"					
						+" order by cv.cava_id asc"
						+"  ) r2"
						+"  "
						+"  union all"
						+" "
						+" select r3.vector"
						+"       ,r3.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"    if (cv.cava_valor_code in (select fk_dist_id"
						+"                                      from oferta_laboral"
						+"                                     where ofla_id = :oflaId) ,1,0) vector"
						+"     ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'ubica'"						
						+" order by cv.cava_id asc"
						+"  ) r3"
						+"  "
						+"  union all"
						+" "
						+" select r4.vector"
						+"       ,r4.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"    if (ol.fk_esci_id= cv.cava_valor_code,1,0) vector"
						+"    ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+"     ,oferta_laboral      ol"
						+" where 1=1"
						+" and ol.ofla_id = :oflaId"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'estciv'"						
						+" order by cv.cava_id asc"
						+"  ) r4"
						+"  "
						+"  union all"
						+" "
						+" select r5.vector"
						+"       ,r5.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"        if(cv.cava_valor_code in ("
						+"                                   SELECT oce.fk_cees_id"
						+"                                    FROM oferta_laboral        ol"
						+"                                        ,oferta_centro_estudio oce"
						+"                                   WHERE ol.ofla_id = :oflaId"
						+"                                    and oce.fk_ofla_id = ol.ofla_id"
						+"                                  ) ,1,0)  vector"
						+" 	 ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'centest'"						
						+" order by cv.cava_id asc"
						+" "
						+"  ) r5"
						+"  "
						+"  union all"
						+" "
						+" select r6.vector"
						+"       ,r6.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"        if (cv.cava_cota_minima <= (select ofcu_nota from oferta_curso  where fk_ofla_id = :oflaId and fk_curs_id = cux.curs_id)"
						+"        and cv.cava_cota_maxima >= (select ofcu_nota from oferta_curso  where fk_ofla_id = :oflaId and fk_curs_id = cux.curs_id),1,0) vector"
						+" 	   ,concat(cv.cava_nr_nombre_columna,'-',cux.curs_id) columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+"     ,curso cux"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'notacur'"					
						+" order by cux.curs_id , cv.cava_id asc"
						+"  ) r6"
						+"  "
						+"  union all"
						+" "
						+" select r7.vector"
						+"       ,r7.columna_destino"
						+"  from"
						+"  ("
						+"  select"
						+"       if (cv.cava_valor_code in (SELECT eg.fk_grad_id"
						+"                                    FROM oferta_estudio      oe"
						+"                                        ,estudio_generico    eg"
						+"                                   WHERE eg.esge_id = egx.esge_id"
						+"                                    and eg.esge_id = oe.fk_esge_id"
						+"                                    and oe.fk_ofla_id = :oflaId),1,0) vector"
						+" 		,concat(cv.cava_nr_nombre_columna,'-',egx.esge_id) columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" 	 ,estudio_generico egx"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'gradoest'"					
						+" order by egx.esge_id, cv.cava_id asc"
						+"  ) r7"
						+"  "
						+"  union all"
						+" "
						+" select r8.vector"
						+"       ,r8.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"        if ( cv.cava_cota_minima <= (select oe.ofes_porcentaje_avance"
						+"                                      from oferta_estudio      oe"
						+"                                      where oe.fk_esge_id = egx.esge_id"
						+"                                       and oe.fk_ofla_id = :oflaId"
						+"                                      limit 1)"
						+"         and cv.cava_cota_maxima >= (select oe.ofes_porcentaje_avance"
						+"                                      from oferta_estudio      oe"
						+"                                      where oe.fk_esge_id = egx.esge_id"
						+"                                       and oe.fk_ofla_id = :oflaId"
						+"                                      limit 1),1,0) vector"
						+" 		,concat(cv.cava_nr_nombre_columna,'-',egx.esge_id) columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+"     ,estudio_generico  egx"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'avanceest'"					
						+" order by egx.esge_id, cv.cava_id asc"
						+"  ) r8"
						+"  "
						+"  union all"
						+" "
						+" select r9.vector"
						+"       ,r9.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"       if (cv.cava_valor_code in (select fk_idio_id from oferta_idioma where fk_ofla_id = :oflaId ) ,1,0) vector"
						+" 	  ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'idioma'"						
						+" order by cv.cava_id asc"
						+"  ) r9"
						+"  "
						+"  union all"
						+" "
						+" select r10.vector"
						+"       ,r10.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"         if (cv.cava_valor_code in (select fk_niid_id from oferta_idioma where fk_ofla_id = :oflaId and fk_idio_id = idx.idio_id ) ,1,0) vector"
						+" 		,concat(cv.cava_nr_nombre_columna,'-',idx.idio_id) columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+"     ,idioma idx"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'nivelidiom'"						
						+" order by idx.idio_id, cv.cava_id asc"
						+"  ) r10"
						+"  "
						+"  union all"
						+" "
						+" select r11.vector"
						+"       ,r11.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"         if (cv.cava_valor_code in (select pu.fk_nipu_id"
						+"                                      from oferta_laboral ol,"
						+"                                           puesto pu"
						+"                                     where 1=1"
						+"                                      and ol.fk_pues_id = pu.pues_id"
						+"                                      and ol.ofla_id = :oflaId"
						+" 									 and pu.pues_estado = 'V') ,1,0) vector"
						+" 		,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+"  and cs.crse_id = cv.fk_crse_id"
						+"  and cs.crse_code = 'nivelexp'"						
						+" order by cv.cava_id asc"
						+"  ) r11"
						+"  "
						+"  union all"
						+" "
						+" select r12.vector"
						+"       ,r12.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"         if (cv.cava_cota_minima <= (select sum(ofla_tiempo_experiencia)"
						+"                                      from oferta_laboral      ol"
						+"                                          ,puesto              pu"
						+"                                     where ol.ofla_id = :oflaId"
						+"                                       and pu.pues_id = ol.fk_pues_id"
						+"                                       and pu.fk_nipu_id = npx.nipu_id"
						+"                                       and pu.pues_estado = 'V'  )"
						+"             and cv.cava_cota_maxima >= (select sum(ofla_tiempo_experiencia)"
						+"                                      from oferta_laboral      ol"
						+"                                          ,puesto              pu"
						+"                                     where ol.ofla_id = :oflaId"
						+"                                       and pu.pues_id = ol.fk_pues_id"
						+"                                       and pu.fk_nipu_id = npx.nipu_id"
						+"                                       and pu.pues_estado = 'V' )"
						+"            ,1"
						+"            ,0) vector"
						+" 		 ,concat(cv.cava_nr_nombre_columna,'-',npx.nipu_id) columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+"     ,nivel_puesto        npx"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'tiempoexp'"					
						+" order by npx.nipu_id, cv.cava_id asc"
						+"  ) r12"
						+"  "
						+"  union all"
						+" "
						+" select r13.vector"
						+"       ,r13.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"        if (cv.cava_valor_code in (select fk_cono_id from oferta_conocimiento where fk_ofla_id = :oflaId ) ,1,0) vector"
						+" 	  ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'conocim'"					
						+" order by cv.cava_id asc"
						+"  ) r13"
						+"  "
						+"  union all"
						+" "
						+" select r14.vector"
						+"       ,r14.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"         if (cv.cava_valor_code in (select fk_nico_id from oferta_conocimiento where fk_ofla_id = :oflaId"
						+"                                      and fk_cono_id = cox.cono_id) ,1,0) vector"
						+" 		,concat(cv.cava_nr_nombre_columna,'-',cox.cono_id) columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+"     ,conocimiento        cox"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'nivelcono'"					
						+" and cox.cono_estado = 'V'"
						+" order by cox.cono_id, cv.cava_id asc"
						+"  ) r14");
		
		query.setParameter("oflaId", ofertaLaboral.getOflaId());
		
		List<Object[]> list = query.list();
		
		for (int i = 0; i < list.size(); i++) {
			Integer value = (Integer)list.get(i)[0];
			String key = (String)list.get(i)[1];
			
			System.out.println(key+" "+value);			
			
			result.put(key, value);
		}
		
		return result;
	}
	
	public LinkedHashMap<String, Integer> getVectorPostulantPreference(Postulante postulante){
		LinkedHashMap<String, Integer> result = new LinkedHashMap<String, Integer>();
		

		SQLQuery query = getSessionFactory()
				.getCurrentSession().createSQLQuery(""
						+" select r1.vector"
						+"       ,r1.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"        if (cv.cava_valor_code in (select fk_bene_id from postulante_beneficio where fk_post_id = :postId ) ,1,0) vector"
						+" 	   ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'beneflab'"
						+" order by cv.cava_id asc"
						+"  ) r1"
						+"  "
						+"  union all"
						+"  "
						+" select r2.vector"
						+"       ,r2.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"         if (cv.cava_cota_minima <= (select post_salario from postulante where post_id = :postId)"
						+"             and cv.cava_cota_maxima >= (select post_salario from postulante where post_id = :postId)"
						+"            ,1"
						+"            ,0) vector"
						+" 		,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'salario'"
						+" order by cv.cava_id asc"
						+"  ) r2"
						+"  "
						+"  union all"
						+"  "
						+"  select r3.vector"
						+"        ,r3.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"        if (cv.cava_valor_code in (select fk_tiho_id from postulante where post_id = :postId ) ,1,0) vector"
						+" 	   ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'tipohor'"
						+" order by cv.cava_id asc"
						+"  ) r3"
						+"  "
						+"  union all"
						+"  "
						+"  select r4.vector"
						+"        ,r4.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"   if (cv.cava_valor_code in (select fk_sect_id from postulante where post_id = :postId ) ,1,0) vector"
						+"   ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'sector'"
						+" order by cv.cava_id asc"
						+"  ) r4"
						+"  "
						+"  union all"
						+"  "
						+"  select r5.vector"
						+"        ,r5.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"     if (cv.cava_valor_code in (select fk_dior_id from postulante where post_id = :postId ) ,1,0) vector"
						+" 	,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'dimensemp'"
						+" order by cv.cava_id asc"
						+"  ) r5"
						+"  "
						+"  union all"
						+"  "
						+"  select r6.vector"
						+"        ,r6.columna_destino"
						+"  from"
						+"  ("
						+" select"
						+"    if (cv.cava_valor_code in (select fk_nipu_id from postulante where post_id = :postId ) ,1,0) vector"
						+"    ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'tipopuest'"
						+" order by cv.cava_id asc"
						+"  ) r6");
		
		query.setParameter("postId", postulante.getPostId());
		
		List<Object[]> list = query.list();
		
		for (int i = 0; i < list.size(); i++) {
			Integer value = (Integer)list.get(i)[0];
			String key = (String)list.get(i)[1];
			
			System.out.println(key+" "+value);			
			
			result.put(key, value);
		}
		
		return result;						 
	}
	
	public LinkedHashMap<String, Integer> getVectorPostulantSelfDescription(Postulante postulante){
		LinkedHashMap<String, Integer> result = new LinkedHashMap<String, Integer>();
		

		SQLQuery query = getSessionFactory()
				.getCurrentSession().createSQLQuery(""
						+" select r1.vector"
						+"      ,r1.columna_destino"
						+" from"
						+" ("
						+" select"
						+" if (ps.post_sexo = cv.cava_valor_code,1,0) vector"
						+" ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+"     ,postulante          ps"
						+" where 1=1"
						+" and ps.post_id = :postId"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'sexo'"
						+" order by cv.cava_id asc"
						+" "
						+"  ) r1"
						+"  "
						+"  union all"
						+" "
						+" select r2.vector"
						+"       ,r2.columna_destino"
						+" from"
						+" ("
						+" select"
						+"    if (ps.post_edad >= cv.cava_cota_minima"
						+"     and ps.post_edad <= cv.cava_cota_maxima,1,0) vector"
						+"    ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+"     ,postulante          ps"
						+" where 1=1"
						+" and ps.post_id = :postId"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'edad'"
						+" order by cv.cava_id asc"
						+" ) r2"
						+" "
						+"  union all"
						+" "
						+" select r3.vector"
						+"       ,r3.columna_destino"
						+" from"
						+" ("
						+" select"
						+"         if (cv.cava_valor_code in ("
						+"                                   select max(resi_id) resi_id"
						+"                                    from residencia"
						+"                                   where fk_post_id = :postId"
						+"                                    and resi_activo = true) ,1,0) vector"
						+"         ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'ubica'"
						+" order by cv.cava_id asc"
						+" ) r3"
						+" "
						+"  union all"
						+" "
						+" select r4.vector"
						+"       ,r4.columna_destino"
						+" from"
						+" ("
						+" select"
						+"    if (p.fk_esci_id= cv.cava_valor_code,1,0) vector"
						+"    ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+"     ,postulante          p"
						+" where 1=1"
						+" and p.post_id = :postId"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'estciv'"
						+" order by cv.cava_id asc"
						+" ) r4"
						+" "
						+"  union all"
						+" "
						+" select r5.vector"
						+"       ,r5.columna_destino"
						+" from"
						+" ("
						+" select"
						+"        if(cv.cava_valor_code in ("
						+"                                   SELECT es.fk_cees_id"
						+"                                    FROM actividad_academica aa"
						+"                                        ,estudio             es"
						+"                                   WHERE es.estu_id = aa.fk_estu_id"
						+"                                         and aa.fk_post_id = :postId"
						+" 										and es.estu_estado = 'V'"
						+"                                  ) ,1,0)  vector"
						+" 	  ,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'centest'"
						+" order by cv.cava_id asc"
						+" ) r5"
						+" "
						+"  union all"
						+" "
						+" select r6.vector"
						+"       ,r6.columna_destino"
						+" from"
						+" ("
						+" select"
						+"        if (cv.cava_cota_minima <= (select pocu_nota from postulante_curso  where fk_post_id = :postId and fk_curs_id = cux.curs_id)"
						+"        and cv.cava_cota_maxima >= (select pocu_nota from postulante_curso  where fk_post_id = :postId and fk_curs_id = cux.curs_id),1,0) vector"
						+" 	   ,concat(cv.cava_nr_nombre_columna,'-',cux.curs_id) columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+"     ,curso cux"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'notacur'"
						+" order by cux.curs_id , cv.cava_id asc"
						+" ) r6"
						+" "
						+"  union all"
						+" "
						+" select r7.vector"
						+"       ,r7.columna_destino"
						+" from"
						+" ("
						+" select"
						+"      if (cv.cava_valor_code in (SELECT eg.fk_grad_id"
						+"                                    FROM actividad_academica aa"
						+"                                        ,estudio             es"
						+"                                        ,estudio_generico    eg"
						+"                                   WHERE eg.esge_id = egx.esge_id"
						+"                                    and eg.esge_id = es.fk_esge_id"
						+"                                    and es.estu_id = aa.fk_estu_id"
						+"                                    and aa.fk_post_id = :postId"
						+" 	 							   and es.estu_estado = 'V'),1,0) vector"
						+" 	 ,concat(cv.cava_nr_nombre_columna,'-',egx.esge_id) columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" 	,estudio_generico egx"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'gradoest'"
						+" order by egx.esge_id, cv.cava_id asc"
						+" "
						+" ) r7"
						+" "
						+"  union all"
						+" "
						+" select r8.vector"
						+"       ,r8.columna_destino"
						+" from"
						+" ("
						+" select"
						+"        if ( cv.cava_cota_minima <= (select aa.acac_porcentaje_avance"
						+"                                      from actividad_academica aa"
						+"                                          ,estudio             es"
						+"                                      where es.fk_esge_id = egx.esge_id"
						+"                                       and es.estu_id = aa.fk_estu_id"
						+"                                       and aa.fk_post_id = :postId"
						+" 									  and es.estu_estado = 'V'"
						+"                                      limit 1)"
						+"         and cv.cava_cota_maxima >= (select aa.acac_porcentaje_avance"
						+"                                      from actividad_academica aa"
						+"                                          ,estudio             es"
						+"                                      where es.fk_esge_id = egx.esge_id"
						+"                                       and es.estu_id = aa.fk_estu_id"
						+"                                       and aa.fk_post_id = :postId"
						+" 									  and es.estu_estado = 'V'"
						+"                                      limit 1),1,0) vector"
						+" 	 ,concat(cv.cava_nr_nombre_columna,'-',egx.esge_id) columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+"     ,estudio_generico  egx"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'avanceest'"
						+" order by egx.esge_id, cv.cava_id asc"
						+" ) r8"
						+" "
						+"  union all"
						+" "
						+" select r9.vector"
						+"       ,r9.columna_destino"
						+" from"
						+" ("
						+" select"
						+"         if (cv.cava_valor_code in (select fk_idio_id from postulante_idioma where fk_post_id = :postId ) ,1,0) vector"
						+" 		,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'idioma'"
						+" order by cv.cava_id asc"
						+" ) r9"
						+" "
						+"  union all"
						+" "
						+" select r10.vector"
						+"       ,r10.columna_destino"
						+" from"
						+" ("
						+" select"
						+"         if (cv.cava_valor_code in (select fk_niid_id from postulante_idioma where fk_post_id = :postId and fk_idio_id = idx.idio_id ) ,1,0) vector"
						+" 		,concat(cv.cava_nr_nombre_columna,'-',idx.idio_id) columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+"     ,idioma idx"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'nivelidiom'"
						+" order by idx.idio_id, cv.cava_id asc"
						+" ) r10"
						+" "
						+"  union all"
						+" "
						+" select r11.vector"
						+"       ,r11.columna_destino"
						+" from"
						+" ("
						+" select"
						+"         if (cv.cava_valor_code in (select pu.fk_nipu_id"
						+"                                      from experiencia_laboral el,"
						+"                                           puesto pu"
						+"                                     where 1=1"
						+"                                      and el.fk_pues_id = pu.pues_id"
						+"                                      and el.fk_post_id = :postId"
						+" 									 and pu.pues_estado = 'V') ,1,0) vector"
						+" 		,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+"  and cs.crse_id = cv.fk_crse_id"
						+"  and cs.crse_code = 'nivelexp'"
						+" order by cv.cava_id asc"
						+" ) r11"
						+" "
						+"  union all"
						+" "
						+" select r12.vector"
						+"       ,r12.columna_destino"
						+" from"
						+" ("
						+" select"
						+"         if (cv.cava_cota_minima <= (select sum(exla_tiempo_meses)"
						+"                                      from experiencia_laboral el"
						+"                                          ,puesto              pu"
						+"                                     where el.fk_post_id = :postId"
						+"                                       and pu.pues_id = el.fk_pues_id"
						+"                                       and pu.fk_nipu_id = npx.nipu_id"
						+"                                       and pu.pues_estado = 'V')"
						+"             and cv.cava_cota_maxima >= (select sum(exla_tiempo_meses)"
						+"                                      from experiencia_laboral el"
						+"                                          ,puesto              pu"
						+"                                     where el.fk_post_id = :postId"
						+"                                       and pu.pues_id = el.fk_pues_id"
						+"                                       and pu.fk_nipu_id = npx.nipu_id"
						+" 									  and pu.pues_estado = 'V')"
						+"            ,1"
						+"            ,0) vector"
						+" 		,concat(cv.cava_nr_nombre_columna,'-',npx.nipu_id) columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+"     ,nivel_puesto        npx"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'tiempoexp'"
						+" order by npx.nipu_id, cv.cava_id asc"
						+" ) r12"
						+" "
						+"  union all"
						+" "
						+" select r13.vector"
						+"       ,r13.columna_destino"
						+" from"
						+" ("
						+" select"
						+"         if (cv.cava_valor_code in (select fk_cono_id from postulante_conocimiento where fk_post_id = :postId ) ,1,0) vector"
						+" 		,cv.cava_nr_nombre_columna columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'conocim'"
						+" order by cv.cava_id asc"
						+" ) r13"
						+" "
						+"  union all"
						+" "
						+" select r14.vector"
						+"       ,r14.columna_destino"
						+" from"
						+" ("
						+" select"
						+"         if (cv.cava_valor_code in (select fk_nico_id from postulante_conocimiento where fk_post_id = :postId"
						+"                                      and fk_cono_id = cox.cono_id) ,1,0) vector"
						+" 		,concat(cv.cava_nr_nombre_columna,'-',cox.cono_id) columna_destino"
						+" from categoria_valor     cv"
						+"     ,criterio_seleccion  cs"
						+"     ,conocimiento        cox"
						+" where 1=1"
						+" and cs.crse_id = cv.fk_crse_id"
						+" and cs.crse_code = 'nivelcono'"
						+" and cox.cono_estado = 'V'"
						+" order by cox.cono_id, cv.cava_id asc"
						+" ) r14");
		
		query.setParameter("postId", postulante.getPostId());
		
		List<Object[]> list = query.list();
		
		for (int i = 0; i < list.size(); i++) {
			Integer value = (Integer)list.get(i)[0];
			String key = (String)list.get(i)[1];
			
			System.out.println(key+" "+value);			
			
			result.put(key, value);
		}
		
		return result;			
	}
	
	
	
	//getters and setters
	
	public SessionFactory getSessionFactory() {
		return sessionFactory;
	}
	
	public void setSessionFactory(SessionFactory sessionFactory) {
        this.sessionFactory = sessionFactory;
    }
}
